### PR TITLE
Fix HTML code not work on bind mode

### PR DESCRIPTION
**Pull request by nguyenvanduocit**

### CODE REVIEW

**Comment by metachris** [comment]
Thanks for the contribution! In which Browser/Version did you experience this problem?

**Comment by nguyenvanduocit** [comment]
Chrome 59.0.3043.0
The code:
```
<pre v-highlightjs="code"><code class="HTML"></code></pre>
....
let code = '<meta charset="utf-8">'
```

**Comment by metachris** [comment]
Thanks, this is merged and released. 👍

**Comment by nguyenvanduocit** [comment]
Thank you

**Pull request merged**
